config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'home#index'

  resources :clients do 
    resources :check_ins
  end

  resources :employees
  resources :equipment

  resources :pollock3
  resources :pollock7
  resources :icq

  resources :assessments do
    collection do
      get 'clients'
    end
  end

  get 'cycles/update_exercises', as: 'update_exercises'

  namespace :api do
    devise_for :users

    resources :gymcards do
      resources :cycles
    end

    resources :assessments
    resources :clients do 
      resources :check_ins
    end
  end  

  resources :gymcards do
    resources :cycles
    collection do
      get 'clients'
    end
  end
end

app/models/assessment.rb
class Assessment < ApplicationRecord
  belongs_to :employee, foreign_key: 'employee_id'
  belongs_to :client, foreign_key: 'client_id'

  scope :undone, -> { where(done: false) }
  scope :overdue, -> { undone.where('next_assessment_date < ?', Date.today) }
  scope :in_day, -> { undone.where('next_assessment_date >= ?', (Date.today + 30.days)) }
  scope :next_to_expire, -> { undone.where(next_assessment_date: (Date.today..(Date.today + 30.days))) }

  def client_age
    client.try(:age)
  end

  def mark_as_done
    last_assessment = Assessment.where(client_id: client.id).where.not(id: self.id).last
    last_assessment.update_attribute(:done, true) if last_assessment
  end
  after_save :mark_as_done

  self.per_page = 5
end

app/controllers/api/assessments_controller.rb
class Api::AssessmentsController < Api::BaseController
  def index
    @client      = Client.where(authentication_token: params[:user_token]).first
    @assessments = @client.assessments.all
  end
end

app/controllers/assessments_controller.rb
# coding: utf-8
class AssessmentsController < ApplicationController
  before_action :set_assessment, only: [:show, :edit, :destroy]

  def clients
    if params[:filter]
      @clients = Client.where(id: filter_by_ids).order('name ASC').paginate(:page => params[:page])
    elsif params[:search] && params[:search].key?(:q)
      q = params[:search][:q]
      @clients = Client.where('name LIKE ?', "%#{q}%").order('name ASC').paginate(:page => params[:page])
    else
      @clients = Client.all.order('name ASC').paginate(:page => params[:page])
    end
  end

  # GET /assessments
  # GET /assessments.json
  def index
    @client      = Client.find(params[:client_id])
    @assessments = @client.assessments
  end

  def new
    @client     = Client.find(params[:client_id])
    @assessment = @client.assessments.build
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_assessment
    @client     = Client.find(params[:client_id])
    @assessment = @client.assessments.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def assessment_params
    params.require(:assessment).permit(:client_id, :employee_id, :bodyfat, :ideal_max, :ideal_min, :weight, :height, :ideal_min_weight, :ideal_max_weight, :fat_weight, :lean_body_mass, :fat_body_mass, :tricipital, :peitoral, :subescapular, :axilar_media, :suprailiaca, :abdominal, :coxa, :neck, :shoulder, :chest, :waist, :abdomen, :hip, :right_arm, :left_arm, :right_forearm, :left_forearm, :right_thigh, :left_thigh, :right_calf, :left_calf, :result)
  end


  def filter_by_ids
    q =  params[:filter]
    case q
    when "in_day"
      return Assessment.in_day.map(&:client_id)
    when "next_to_expire"
      return Assessment.next_to_expire.map(&:client_id)
    when "overdue"
      return Assessment.overdue.map(&:client_id)
    end
  end
end

app/helpers/assessments_helper.rb
module AssessmentsHelper

  def edit_path_by_type(assessment, client_id)
    case assessment.type
    when "Pollock3"
      edit_pollock3_path(assessment, client_id: client_id)
    when "Pollock7"
      edit_pollock7_path(assessment, client_id: client_id)
    when "IcqAssessment"
      edit_icq_path(assessment, client_id: client_id)
    else
      edit_assessment_path(assessment, client_id: client_id)
    end
  end

  def show_path_by_type(assessment, client_id, format = :html)
    case assessment.type
    when "Pollock3"
      pollock3_path(assessment, client_id: client_id, format: format)
    when "Pollock7"
      pollock7_path(assessment, client_id: client_id, format: format)
    when "IcqAssessment"
      icq_path(assessment, client_id: client_id, format: format)
    else
      assessment_path(assessment, client_id: client_id, format: format)
    end
  end

  def destroy_path_by_type(assessment, client_id)
    case assessment.type
    when "Pollock3"
      pollock3_path(assessment, client_id)
    when "Pollock7"
      pollock7_path(assessment, client_id)
    when "IcqAssessment"
      icq_path(assessment, client_id)
    else
      assessment_path(assessment, client_id)
    end
  end
end

app/views/assessments/clients.html.erb
<!-- Visão geral do site -->
<div class="panel panel-default">
	<div class="panel-heading main-color-bg">
		<h3 class="panel-title">Clientes</h3>

	</div>
	<div class="panel-body">
		<div class="row">
			<div class="col-md-12">
				<%= simple_form_for :search, url: clients_path, method: :get do |f| %>
				<div class="input-group">
					<%= f.input :q, label: false,  placeholder: 'Pesquisar cliente', class: "form-control" %>
					<div class="input-group-btn">
						<%= f.submit 'Buscar', class: 'btn btn-default' do %>
						<span class="glyphicon glyphicon-search"></span>
						<% end %>
					</div>
				</div>
				<% end  %>
			</div>
		</div>
		<br>
		<table class ="table table-striped table-hover" >
			<thead>
				<tr>
					<th>Nome</th>
					<th>Gênero</th>
					<th>Data de Nascimento</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @clients.each do |client| %>
				<tr>
					<td class="td-name"><%= image_tag client.avatar.url(:medium), class: 'img-responsive img-thumbnail img-circle img-table' %> <%= client.name.capitalize %></td>
					<td><%= client.gender %></td>
					<td><%= date_formatter(client.birth_date) %></td>
					<td><%= link_to 'exibir', assessments_path(client_id: client.id), class: "btn btn-default" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<div class="center">
			<%= will_paginate @clients, previous_label: '« Anterior', next_label: 'Proxima »', renderer: BootstrapPagination::Rails %>
		</div>
	</div>
</div>

app/views/assessments/index.html.erb
<!-- Visão geral do site -->
<div class="panel panel-default">
  <div class="panel-heading main-color-bg">
    <h3 class="panel-title"><%= @client.name %> - <%= date_formatter(@client.birth_date) %></h3>
  </div>
  <div class="panel-body">
    <table class ="table table-striped table-hover" >
      <thead>
        <tr>
          <th>Cliente</th>
          <th>Tipo de avaliação</th>
          <th>Data da avaliação</th>
          <th>Próxima avaliação</th>
          <th colspan="4"></th>
        </tr>
      </thead>

      <tbody>
        <% @assessments.each do |assessment| %>
        <tr>
          <td><%= assessment.client.name %></td>
          <td><%= translate_type(assessment.type) %></td>
          <td><%= date_formatter(assessment.created_at) %></td>
          <td><%= date_formatter(assessment.next_assessment_date) %></td>
          <td><%= link_to 'exibir', show_path_by_type(assessment, @client.id), class: "btn btn-default" %></td>
          <td><%= link_to 'editar', edit_path_by_type(assessment, @client.id), class: "btn btn-default" %></td>
          <td><%= link_to 'download', show_path_by_type(assessment, @client.id, :pdf), class: "btn btn-primary", target: '_blank' %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

  </div>

</div>
<%= link_to 'Nova avaliação', new_assessment_path(client_id: @client.id), class: 'btn btn-success col-md-12' %>

app/views/assessments/new.html.erb
<!-- Visão geral do site -->
<div class="panel panel-default">
  <div class="panel-heading main-color-bg">
    <h3 class="panel-title">Nova Avaliação</h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="btn-group group-bottom col-xs-11 col-center-block" role="group" aria-label="...">
        <%= link_to "Indice Cintura Quadril", new_icq_path(client_id: @client.id), class: 'btn btn-default' %>
        <%= link_to "Protocolo Pollock 3 dobras", new_pollock3_path(client_id: @client.id), class: 'btn btn-default' %>
        <%= link_to "Protocolo Pollock 7 dobras", new_pollock7_path(client_id: @client.id), class: 'btn btn-default' %>
      </div>
    </div>

    <%= link_to 'Voltar', assessments_path(client_id: @client.id) %>
  </div>
</div>