config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'home#index'

  resources :clients do 
    resources :check_ins
  end

  resources :employees
  resources :equipment

  resources :pollock3
  resources :pollock7
  resources :icq

  resources :assessments do
    collection do
      get 'clients'
    end
  end

  get 'cycles/update_exercises', as: 'update_exercises'

  namespace :api do
    devise_for :users

    resources :gymcards do
      resources :cycles
    end

    resources :assessments
    resources :clients do 
      resources :check_ins
    end
  end  

  resources :gymcards do
    resources :cycles
    collection do
      get 'clients'
    end
  end
end

app/models/assessment.rb
class Assessment < ApplicationRecord
  belongs_to :employee, foreign_key: 'employee_id'
  belongs_to :client, foreign_key: 'client_id'

  scope :undone, -> { where(done: false) }
  scope :overdue, -> { undone.where('next_assessment_date < ?', Date.today) }
  scope :in_day, -> { undone.where('next_assessment_date >= ?', (Date.today + 30.days)) }
  scope :next_to_expire, -> { undone.where(next_assessment_date: (Date.today..(Date.today + 30.days))) }

  def client_age
    client.try(:age)
  end

  def mark_as_done
    last_assessment = Assessment.where(client_id: client.id).where.not(id: self.id).last
    last_assessment.update_attribute(:done, true) if last_assessment
  end
  after_save :mark_as_done

  self.per_page = 5
end

app/models/check_in.rb
class CheckIn < ApplicationRecord
  belongs_to :client
end

app/models/client.rb
# coding: utf-8
class Client < User
  acts_as_token_authenticatable

  has_attached_file :avatar, styles: { medium: "300x300#", thumb: "100x100#" }, default_url: "https://click.dj/img/no-avatar.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  has_attached_file :attachment
  has_many :gymcards
  has_many :check_ins
  has_many :assessments
  has_many :pollock3
  has_many :pollock7
  has_many :icq_assessments

  def age
    value = Time.now.year - self.birth_date.year
    
    return 'Não especificado' if value <= 0

    value
  end

  private

  def password_required?
    false
  end
  self.per_page = 5

end

app/models/cycle.rb
class Cycle < ApplicationRecord
  has_many :workouts
  accepts_nested_attributes_for :workouts, reject_if: :all_blank,
                                allow_destroy: true
end

app/models/employee.rb
class Employee < User
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "https://click.dj/img/no-avatar.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  validates :name, presence: { message: 'Campo não pode ficar em branco.' }
  validates :email, presence: { message: 'Inserir um e-mail válido.' }, uniqueness:{ message:'E-mail já cadastrado.' }
  validates :password, presence: { message: 'Campo não pode ficar em branco.' }
  validates :position, presence: true
  validates :birth_date, presence: true
  validates :rg, allow_blank: true, numericality: { only_integer: true, message: 'Somente números.' }
  validates :cpf, allow_blank: true, uniqueness:{ message:'CPF já cadastrado' }, numericality: { only_integer: true, message: 'Somente números.' }
  validates :telephone, presence: true, numericality: { only_integer: true, message: 'Somente números.' }
  validates :admission_date, presence: true


  before_save :upcase_name

  has_many :gymcards

  def upcase_name
    self.name = self.name.upcase
  end

  private

  self.per_page = 5
end

app/models/equipment.rb
class Equipment < ApplicationRecord
	validates :name, presence: true
	validates :name, uniqueness:{
		case_sensitive: false,
		message:'Equipamento já cadastrado'
	}
	validates :quantity, presence: true, numericality:{
		greater_than: 0,
		message:'Precisa ser maior que 0'
	}
	validates :aquisition_date, presence: true
	validates :weight, presence: true, numericality:{
		greater_than: 0,
		message:'Precisa ser maior que 0'
	}
	validates :max_weight, presence: true, numericality:
	{	greater_than: 0,
		message:'Precisa ser maior que 0'
	}

	before_save :upcase_name

	def upcase_name
		self.name = self.name.upcase
	end
	self.per_page = 5
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :grouptype
end

app/models/grouptype.rb
class Grouptype < ApplicationRecord
	has_many :exercises
	
end

app/models/gymcard.rb
class Gymcard < ApplicationRecord
  belongs_to :employee, foreign_key: 'employee_id'
  belongs_to :client, foreign_key: 'client_id'
  has_many :cycles

  accepts_nested_attributes_for :cycles

  scope :active, -> { where(active: true) }
  self.per_page = 5
end

app/models/icq.rb
class Icq < ApplicationRecord
end

app/models/icq_assessment.rb
class IcqAssessment < Assessment
end

app/models/imc.rb
class Imc < ApplicationRecord
end

app/models/pollock3.rb
class Pollock3 < Assessment
end

app/models/pollock7.rb
class Pollock7 < Assessment
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
  class User < ApplicationRecord
  acts_as_token_authenticatable
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  has_many :gymcards, foreign_key: 'employee_id'
  has_many :assessments, foreign_key: 'employee_id'

  before_save :set_role

  def role_admin?
    has_role? "admin"
  end

  def employee?
    has_role? "employee"
  end

  def student?
    has_role? "Student"
  end

  def set_role
    case self.type
    when self.admin? then
      add_role "admin"
    when "Employee" then
      add_role "employee"
    when "Client" then
      add_role "student"
    end
  end
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :equipment, optional: true
  belongs_to :cycle, optional: true
  belongs_to :grouptype, optional: true
  belongs_to :exercise, optional: true
 end

app/controllers/cycles_controller.rb
class CyclesController < ApplicationController
  before_filter :load_gymcard, except: [:update_exercises]

  def index
    @cycles = @gymcard.cycles
  end

  def new
    @cycle = @gymcard.cycles.build
  end

  def create
    @cycle = @gymcard.cycles.build(cycle_params)

    if @cycle.save
      redirect_to gymcard_cycles_path(@gymcard),
                  notice: 'Ciclo criado com sucesso.'
    else
      render :new
    end
  end

  def show
    @cycle = @gymcard.cycles.find(params[:id])
  end

  def edit
    @cycle = @gymcard.cycles.find(params[:id])
  end

  def update
    @cycle = @gymcard.cycles.find(params[:id])

    if @cycle.update_attributes(cycle_params)
      redirect_to gymcard_cycles_path(@gymcard),
                  notice: 'Ciclo edit com sucesso.'
    else
      render :edit
    end
  end

  def update_exercises
    @exercises  = Exercise.where("grouptype_id = ?", params[:grouptype_id])
    @element_id = params[:id]
    respond_to do |format|
      format.js
    end
  end

  private

  def load_gymcard
    @gymcard = Gymcard.find(params[:gymcard_id])
  end

  def cycle_params
    params.require(:cycle).permit(:name, :index, :gymcard_id,
                                  workouts_attributes: [:id,
                                                        :name,
                                                        :serie,
                                                        :sequence,
                                                        :load,
                                                        :equipment_id,
                                                        :obs,
                                                        :_destroy,
                                                        :exercise_id,
                                                        :grouptype_id,
                                                        ])
  end
end

app/helpers/check_ins_helper.rb
module CheckInsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cycles/_exercise.html.erb
<option value="<%= exercise.id %>"><%= exercise.name.titleize %></option>

app/views/cycles/_form.html.erb
<div class="panel-body">
  <%= simple_form_for([@gymcard, @cycle]) do |f| %>
  <div class="form-inputs">
    <%= f.input :name, label: 'Nome:' %>

    <div id='workouts'>
      <%= f.simple_fields_for :workouts do |workout| %>
      <%= render 'workout_fields', :f => workout %>
      <% end %>
      <div class="pull-right">
        <%= link_to_add_association 'Adicionar Exercício', f, :workouts, class: 'btn btn-success' %>
      </div>
    </div>
  </div>
  <br />
  <div class="form-actions">
    <%= f.button :submit, 'Salvar', class: 'btn btn-success' %>
  </div>
  <% end %>
  <br />
  <%= link_to 'Voltar', gymcard_cycles_path(@gymcard) %>
</div>

app/views/cycles/_workout_fields.html.erb
<div class="nested-fields">
  <div class="panel panel-default">
    <div class="panel-heading main-color-bg">
      <h3 class="panel-title">Novo Exercício</h3>
    </div>
    <div class="form-inputs" style="padding: 10px;">
      <div class="row">
        <div class="col-md-3">
          <%= f.association :grouptype, label: 'Grupo Muscular'%>
        </div>
        <div class="col-md-3">
          <%= f.association :exercise, label: 'Exercício' %>
        </div>
        <div class="col-md-3">
          <%= f.input :name, label: 'Nome' %>
        </div>
        <div class="col-md-3">
          <%= f.association :equipment, label: 'Equipamento' %>
        </div>
        <div class="col-md-2">
          <%= f.input :serie, label: 'Série' %>
        </div>
        <div class="col-md-2">
          <%= f.input :sequence, label: 'Sequencia' %>
        </div>
        <div class="col-md-2">
          <%= f.input :load, label: 'Peso' %>
        </div>
        <div class="col-md-12">
          <%= f.input :obs, label: 'Obs' %>

          <%= link_to_remove_association 'Remover Exercício', f, class: 'btn btn-success' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cycles/edit.html.erb
<!-- Visão geral do site -->
<div class="panel panel-default">
  <div class="panel-heading main-color-bg">
    <h3 class="panel-title">Novo Ciclo</h3>
  </div>
  <%= render 'form', locals: {gymcard: @gymcard, cyclo: @cyclo } %>
</div>

app/views/cycles/index.html.erb
<!-- Visão geral do site -->
<div class="panel panel-default">
  <div class="panel-heading main-color-bg">
    <h3 class="panel-title">Ciclos da <%= @gymcard.name %></h3>
  </div>
  <div class="panel-body">
    <table class ="table table-striped table-hover" >
      <thead>
        <tr>
          <th>Name</th>
          <th>Criada em</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>

        <% @cycles.each do |cycle| %>
        <tr>

          <td><%= cycle.name %></td>
          <td><%= date_formatter(cycle.created_at)%></td>
          <td><%= link_to 'Exibir', gymcard_cycle_path(@gymcard, cycle), class: "btn btn-default" %></td>
          <td><%= link_to 'Editar', edit_gymcard_cycle_path(@gymcard, cycle), class: "btn btn-default" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'Voltar', gymcards_path(client_id: @gymcard.client.id) %>
  </div>
</div>

<%= link_to 'Nova Ciclo', new_gymcard_cycle_path(@gymcard), class: 'btn btn-success col-md-12' %>

app/views/cycles/new.html.erb
<!-- Visão geral do site -->
<div class="panel panel-default">
  <div class="panel-heading main-color-bg">
    <h3 class="panel-title">Novo Ciclo</h3>
  </div>
  <%= render 'form', locals: {gymcard: @gymcard, cyclo: @cyclo } %>
</div>

app/views/cycles/show.html.erb
<!-- Visão geral do site -->
<div class="panel panel-default">
  <div class="panel-heading main-color-bg">
    <h3 class="panel-title"><%= @cycle.name %> - <%= @cycle.index %></h3>
  </div>
  <div class="panel-body">
    <div class="col-md-12">
      <table class ="table table-striped table-hover" >
        <thead>
          <tr>
            <th>Nome</th>
            <th>Grupo Muscular</th>
            <th>Exercício</th>
            <th>Equipamento</th>
            <th>Série</th>
            <th>Sequência</th>
            <th>Peso</th>
            <th>obs</th>
            <th colspan="1"></th>
          </tr>
        </thead>
        <tbody>
          <% @cycle.workouts.each do |workout| %>
          <tr>
            <td><%= workout.name %></td>
            <td><%= workout.grouptype.try(:name) %></td>
            <td><%= workout.exercise.try(:name) %></td>
            <td><%= workout.equipment.try(:name) %></td>
            <td><%= workout.serie %></td>
            <td><%= workout.sequence %></td>
            <td><%= workout.load %></td>
            <td><%= workout.obs %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <%= link_to 'Voltar', gymcard_cycles_path(@gymcard) %>
    </div>
  </div>
</div>