config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'home#index'

  resources :clients do 
    resources :check_ins
  end

  resources :employees
  resources :equipment

  resources :pollock3
  resources :pollock7
  resources :icq

  resources :assessments do
    collection do
      get 'clients'
    end
  end

  get 'cycles/update_exercises', as: 'update_exercises'

  namespace :api do
    devise_for :users

    resources :gymcards do
      resources :cycles
    end

    resources :assessments
    resources :clients do 
      resources :check_ins
    end
  end  

  resources :gymcards do
    resources :cycles
    collection do
      get 'clients'
    end
  end
end

app/models/client.rb
# coding: utf-8
class Client < User
  acts_as_token_authenticatable

  has_attached_file :avatar, styles: { medium: "300x300#", thumb: "100x100#" }, default_url: "https://click.dj/img/no-avatar.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  has_attached_file :attachment
  has_many :gymcards
  has_many :check_ins
  has_many :assessments
  has_many :pollock3
  has_many :pollock7
  has_many :icq_assessments

  def age
    value = Time.now.year - self.birth_date.year
    
    return 'Não especificado' if value <= 0

    value
  end

  private

  def password_required?
    false
  end
  self.per_page = 5

end

app/controllers/api/clients_controller.rb
class Api::ClientsController < Api::BaseController
  def show
    @client = Client.where(authentication_token: params[:user_token]).first
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    if params[:search] && params[:search].key?(:q)
      q = params[:search][:q]
      @clients = Client.where('name LIKE ?', "%#{q}%").order('name ASC').paginate(:page => params[:page])
    else
      @clients = Client.all.order('name ASC').paginate(:page => params[:page])
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Cliente foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Cliente foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    if @client.active
      @client.update_attribute(:active, false)
      redirect_to clients_path(client_id: @client.id),
      notice: 'Cliente desativado com sucesso'
    elsif !@client.active
      @client.update_attribute(:active, true)
      redirect_to clients_path(client_id: @client.id),
      notice: 'Cliente reativado com sucesso'
    else
      redirect_to clients_path(client_id: @client.id),
      alert: 'Algum problema ocorreu tentando desativar o ciente'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :gender, :birth_date, :rg, :cpf,
       :address, :telephone, :email,
       :disabilities, :blood_type, :allergy,
       :obs, :subscription_date,
       :payment_date, :avatar,
       :password, :password_confirmation)
    end
  end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= simple_form_for(@client) do |f| %>
<%= f.error_notification %>

<div class="form-inputs">
  <%= f.input :avatar, as: :file, label:'Foto:' %>
  <%= f.input :name, placeholder:'Nome Completo', label: 'Nome:' %>
  <%= f.input :gender, collection: ['Feminino', 'Masculino'], include_blank: false, label: 'Gênero:' %>
  <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length), label: 'Senha:', placeholder: 'Mínimo de 6 dígitos' %>
  <%= f.input :password_confirmation, required: true, label: 'Confirmar senha' %>
  <%= f.input :birth_date, html5:true, label: 'Data de Nascimento:' %>
  <%= f.input :rg, label: 'RG:' %>
  <%= f.input :cpf, label: 'CPF' %>
  <%= f.input :address, label: 'Endereço:' %>
  <%= f.input :telephone, placeholder:'00000000000', label: 'Telefone:' %>
  <p class="help-block">Somente números</p>
  <%= f.input :email, placeholder:'email@email.com', label: 'E-mail:' %>
  <%= f.input :disabilities, label: 'Necessidades Especiais:' %>
  <%= f.input :blood_type, collection: ['Não especificado', 'A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'], include_blank: false, label: 'Tipo Sanguíneo:' %>
  <%= f.input :allergy, label: 'Alergias:' %>
  <%= f.input :obs, label: 'OBS.:' %>
  <%= f.input :subscription_date, html5:true, label: 'Data de Inscrição:' %>
  <%= f.input :payment_date, html5:true, label: 'Data de Pagamento:', type: 'date' %>
  <%= f.input :attachment, as: :file, label: 'Anexo:' %>
</div>

<div class="form-actions">
  <%= f.button :submit, 'Salvar Cliente', class: 'btn btn-success' %>
</div>
<% end %>

app/views/clients/edit.html.erb
<!-- Visão geral do site -->
<div class="panel panel-default">
  <div class="panel-heading main-color-bg">
    <h3 class="panel-title">Editar Cliente</h3>
  </div>
  <div class="panel-body">
    <%= render 'form', client: @client %>

    <%= link_to 'Exibir', @client %> |
    <%= link_to 'Voltar', clients_path %>
  </div>
</div>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<!-- Visão geral do site -->
<div class="panel panel-default">
  <div class="panel-heading main-color-bg">
    <h3 class="panel-title">Clientes</h3>

  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-12">
        <%= simple_form_for :search, url: clients_path, method: :get do |f| %>
        <div class="input-group">
          <%= f.input :q, label: false,  placeholder: 'Pesquisar cliente', class: "form-control" %>
          <div class="input-group-btn">
            <%= f.submit 'Buscar', class: 'btn btn-default' do %>
            <span class="glyphicon glyphicon-search"></span>
            <% end %>
          </div>
        </div>
        <% end  %>
      </div>
    </div>
    <br>
    <table class ="table table-striped table-hover" >
      <thead>
        <tr>
          <th>Nome</th>
          <th>Status</th>
          <th>Telefone</th>
          <th colspan="4"></th>
        </tr>
      </thead>

      <tbody>
        <% @clients.each do |client| %>
        <tr>
          <td class="td-name"><%= image_tag client.avatar.url(:medium), class: 'img-responsive img-thumbnail img-circle img-table' %> <%= client.name.capitalize %></td>  
          <% if client.active? %>
          <td><span class="glyphicon glyphicon-ok status-ok" aria-hidden="true"></span></td>
          <% elsif !client.active?%>
          <td><span class="glyphicon glyphicon-remove status-remove" aria-hidden="true"></span></td>
          <%end %>
          <td><%= client.telephone %></td>
          <td><%= link_to 'exibir', client, class: "btn btn-default" %></td>
          <td><%= link_to 'checkins', client_check_ins_path(client), class: "btn btn-default" %></td>
          <% if client.active? %>
          <td><%= link_to 'editar', edit_client_path(client), class: "btn btn-default" %></td>
          <% end %>
          <% if client.active? %>
          <td><%= link_to 'Desabilitar', client, method: :delete, data: { confirm: 'Você tem certeza que deseja desabilitar?' }, class: "btn btn-danger" %></td>
          <% elsif !client.active?%>
          <td colspan="1"></td>
          <td><%= link_to 'Habilitar', client, method: :delete, data: { confirm: 'Você tem certeza que deseja reabilitar?' }, class: "btn btn-primary", style: "min-width: 91px;" %></td>
          <% end %>
        </tr>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class="center">
    <%= will_paginate @clients, previous_label: '« Anterior', next_label: 'Proxima »', renderer: BootstrapPagination::Rails %>
  </div>
</div>
</div>

<%= link_to 'Novo Cliente', new_client_path, class: 'btn btn-success col-md-12' %>

app/views/clients/new.html.erb
<!-- Visão geral do site -->
<div class="panel panel-default">
	<div class="panel-heading main-color-bg">
		<h3 class="panel-title">Novo Cliente</h3>
	</div>
	<div class="panel-body">

		<%= render 'form', client: @client %>

		<%= link_to 'Voltar', clients_path %>
	</div>
</div>

app/views/clients/show.html.erb
  <!-- Visão geral do site -->
  <div class="panel panel-default">
    <div class="panel-heading main-color-bg">
      <h3 class="panel-title td-name"><%= @client.name.capitalize %></h3>
    </div>
    <div class="panel-body">
      <div class="col-md-12">
        <div class="row">
          <div class="col-xs-2 col-center-block">
            <%= image_tag @client.avatar.url(:medium), class: 'img-responsive img-thumbnail img-circle' %>
          </div>
        </div>

        <table class ="table table-striped table-hover" >
          <tr>
            <th>Gênero:</th>
            <td><%= @client.gender %></td>
          </tr>
        </tr>
        <tr>
          <th>Aniversário:</th>
          <td><%= @client.birth_date %></td>
        </tr>

        <tr>
          <th>RG:</th>
          <td><%= @client.rg %></td>
        </tr>

        <tr>
          <th>CPF:</th>
          <td><%= @client.cpf %></td>
        </tr>

        <tr>
          <th>Endereço:</th>
          <td><%= @client.address %></td>
        </tr>

        <tr>
          <th>Telefone:</th>
          <td><%= @client.telephone %></td>
        </tr>

        <tr>
          <th>Email:</th>
          <td><%= @client.email %></td>
        </tr>

        <tr>
          <th>Necessidades Especiais:</th>
          <td><%= @client.disabilities %></td>
        </tr>

        <tr>
          <th>Tipo Sanguíneo:</th>
          <td><%= @client.blood_type %></td>
        </tr>

        <tr>
          <th>Alergias:</th>
          <td><%= @client.allergy %></td>
        </tr>

        <tr>
          <th>Obs:</th>
          <td><%= @client.obs %></td>
        </tr>

        <tr>
          <th>Data de Inscrição:</th>
          <td><%= @client.subscription_date %></td>
        </tr>

        <tr>
          <th>Data de pagamento:</th>
          <td><%= @client.payment_date %></td>
        </tr>
      </table>
      <%= link_to 'Editar', edit_client_path(@client) %> |
      <%= link_to 'Voltar', clients_path %>
    </div>
  </div>
</div>