config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'home#index'

  resources :clients do 
    resources :check_ins
  end

  resources :employees
  resources :equipment

  resources :pollock3
  resources :pollock7
  resources :icq

  resources :assessments do
    collection do
      get 'clients'
    end
  end

  get 'cycles/update_exercises', as: 'update_exercises'

  namespace :api do
    devise_for :users

    resources :gymcards do
      resources :cycles
    end

    resources :assessments
    resources :clients do 
      resources :check_ins
    end
  end  

  resources :gymcards do
    resources :cycles
    collection do
      get 'clients'
    end
  end
end

app/models/gymcard.rb
class Gymcard < ApplicationRecord
  belongs_to :employee, foreign_key: 'employee_id'
  belongs_to :client, foreign_key: 'client_id'
  has_many :cycles

  accepts_nested_attributes_for :cycles

  scope :active, -> { where(active: true) }
  self.per_page = 5
end

app/controllers/api/gymcards_controller.rb
class Api::GymcardsController < Api::BaseController
  def index
    @client   = Client.where(authentication_token: params[:user_token]).first
    @gymcards = @client.gymcards
  end
end

app/controllers/gymcards_controller.rb
class GymcardsController < ApplicationController
  def clients
    if params[:search] && params[:search].key?(:q)
      q = params[:search][:q]
      @clients = Client.where('name LIKE ?', "%#{q}%").order('name ASC').paginate(:page => params[:page])
    else
      @clients = Client.all.order('name ASC').paginate(:page => params[:page])
    end
  end

  def index
    @client   = Client.find(params[:client_id])
    @gymcards = @client.gymcards
  end

  def new
    @client  = Client.find(params[:client_id])
    @gymcard = Gymcard.new
  end

  def create
    client            = Client.find(gymcards_params[:client_id])
    @gymcard          = Gymcard.create(gymcards_params)
    @gymcard.client   = client
    @gymcard.employee = current_user

    @gymcard.save

    redirect_to gymcards_path(client_id: client.id)
  end

  def show
    @client  = Client.find(params[:client_id])
    @gymcard = @client.gymcards.find(params[:id])

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'gymcard',
               template: 'gymcards/show.pdf.erb'
      end
    end
  end

  def edit

  end

  def update
    respond_to do |format|
      if @gymcard.update(gymcard_params)
        format.html { redirect_to gymcard_path(@gymcard, client_id: @client.id), notice: 'Ficha atualizada com sucesso.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @client  = Client.find(params[:client_id])
    @gymcard = Gymcard.find(params[:id])

    if @gymcard.active
      @gymcard.update_attribute(:active, false)
      redirect_to gymcards_path(client_id: @client.id),
                  notice: 'Ciclo desativado com sucesso'
    elsif !@gymcard.active
      @gymcard.update_attribute(:active, true)
      redirect_to gymcards_path(client_id: @client.id),
                  notice: 'Ciclo reativado com sucesso'
    else
      redirect_to gymcards_pathgym(client_id: @client.id),
                  alert: 'Algum problema ocorreu tentando desativar o ciclo'
    end
  end

  private

  def gymcards_params
    params.require(:gymcard).permit(:name, :client_id, :employee_id)
  end
end

app/views/gymcards/_cycle_fields.html.erb
<div class="nested-fields">
  <%= f.input :index %>
  <div id='workouts'>
    <%= f.simple_fields_for :workouts do |workout| %>
      <%= render 'workout_fields', :f => workout %>
    <% end %>
    <%= link_to_add_association 'Adicionar Exercício', f, :workouts %>
  </div>
  <%= link_to_remove_association 'Remover Ciclo', f %>
</div>

app/views/gymcards/_workout_fields.html.erb
<div class="nested-fields">
	<%= f.input :name, label: 'Nome:' %>
	<%= f.input :serie, label: 'Serie:' %>
	<%= f.input :sequence, label: 'Sequencia:' %>
	<%= f.input :load, label: 'Peso:' %>
	<%= f.input :obs, label: 'Obs.:' %>
	<%= link_to_remove_association 'Remover Exercício', f %>
</div>

app/views/gymcards/clients.html.erb
<p id="notice"><%= notice %></p>

<!-- Visão geral do site -->
<div class="panel panel-default">
  <div class="panel-heading main-color-bg">
    <h3 class="panel-title">Clientes</h3>
    
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-12">
        <%= simple_form_for :search, url: clients_path, method: :get do |f| %>
        <div class="input-group">
          <%= f.input :q, label: false,  placeholder: 'Pesquisar cliente', class: "form-control" %>
          <div class="input-group-btn">
            <%= f.submit 'Buscar', class: 'btn btn-default' do %>
            <span class="glyphicon glyphicon-search"></span>
            <% end %>
          </div>
        </div>
        <% end  %>
      </div>
    </div>
    <br>
    <table class ="table table-striped table-hover" >
      <thead>
        <tr>
          <th>Nome</th>
          <th>Gênero</th>
          <th>Data de Nascimento</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @clients.each do |client| %>
        <tr>
          <td class="td-name"><%= image_tag client.avatar.url(:medium), class: 'img-responsive img-thumbnail img-circle img-table' %> <%= client.name.capitalize %></td>
          <td><%= client.gender %></td>
          <td><%= date_formatter(client.birth_date) %></td>
          <td><%= link_to 'exibir', gymcards_path(client_id: client.id), class: "btn btn-default" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="center">
      <%= will_paginate @clients, previous_label: '« Anterior', next_label: 'Proxima »', renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>

app/views/gymcards/index.html.erb
<!-- Visão geral do site -->
<div class="panel panel-default">
  <div class="panel-heading main-color-bg">
    <h3 class="panel-title"><%= @client.name %> - <%= date_formatter(@client.birth_date) %></h3>
  </div>
  <div class="panel-body">
    <table class ="table table-striped table-hover" >
      <thead>
        <tr>
          <th>Status</th>
          <th>Fichas</th>
          <th>Criada em</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @gymcards.each do |gymcard| %>
        <tr>
          <% if gymcard.active? %>
          <td><span class="glyphicon glyphicon-ok status-ok" aria-hidden="true"></span></td>
          <% elsif !gymcard.active?%>
          <td><span class="glyphicon glyphicon-remove status-remove" aria-hidden="true"></span></td>
          <%end %>
          <td><%= gymcard.name %></td>
          <td><%= date_formatter(gymcard.created_at)%></td>
          <%if gymcard.active?%>
          <td><%= link_to 'Ciclos', gymcard_cycles_path(gymcard), class: "btn btn-default" %></td>
          <% end %>
          <% if gymcard.active? %>
          <td><%= link_to 'Exibir', gymcard_path(gymcard, client_id: @client.id), class: "btn btn-default" %></td>
          <td><%= link_to 'Desabilitar', gymcard_path(gymcard, client_id: @client.id), method: :delete,
            data: { confirm: 'Você tem certeza que deseja desabilitar?' },
            class: "btn btn-danger" %></td>
            <% elsif !gymcard.active?%>
            <td colspan="1"></td>
            <td><%= link_to 'Exibir', gymcard_path(gymcard, client_id: @client.id), class: "btn btn-default" %></td>
            <td><%= link_to 'Habilitar', gymcard_path(gymcard, client_id: @client.id), method: :delete,
              data: { confirm: 'Você tem certeza que deseja habilitar?' },
              class: "btn btn-primary", style: "min-width: 91px;"%></td>
              <% end %>
            <td><%= link_to 'download', gymcard_path(gymcard, :pdf, client_id: @client.id), class: "btn btn-primary", target: '_blank' %></td>
            </tr>
            <% end %>
            </tbody>
        </table>

      </div>
    </div>

    <%= link_to 'Nova Ficha', new_gymcard_path(client_id: @client.id), class: 'btn btn-success col-md-12' %>

app/views/gymcards/new.html.erb
<!-- Visão geral do site -->
<div class="panel panel-default">
  <div class="panel-heading main-color-bg">
    <h3 class="panel-title">Nova Ficha</h3>
  </div>
  <div class="panel-body">
    <%= simple_form_for(@gymcard) do |f| %>
      <div class="form-inputs">
        <%= f.hidden_field :client_id, value: @client.id %>
        <%= f.input :name, label: 'Nome:' %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, 'Criar Ficha', class: 'btn btn-success' %>
      </div>
    <% end %>
    <%= link_to 'Voltar', gymcards_path(client_id: @client.id) %>
  </div>
</div>

app/views/gymcards/show.html.erb
<!-- Visão geral do site -->
<div class="panel panel-default">
  <div class="panel-heading main-color-bg">
    <h1 class="panel-title"><%= @gymcard.name %></h1>
  </div>
  <div class="panel-body">
    <div class="col-md-12">
      <div>
        <table class ="table table-striped table-hover" >
          <tbody>
            <tr>
              <th>Cliente</th>
              <td class="td-name"><%= @gymcard.client.name.capitalize %></td>
            </tr>
            <tr>
              <th>Profissional</th>
              <td class="td-name"><%= @gymcard.employee.name.capitalize %> </td>
            </tr>
          </tbody>
        </table>
      </div>

      <% @gymcard.cycles.each do |cycle| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h1 class="panel-title"><%= cycle.name %></h1>
        </div>
        <div class="panel-body">
          <table class ="table table-striped" >
            <thead>
              <tr>
                <th>Nome:</th>
                <th>Grupo Muscular:</th>
                <th>Exercício:</th>
                <th>Equipamento:</th>
                <th>Série:</th>
                <th>Sequência:</th>
                <th>Peso:</th>
                <th>obs:</th>
              </tr>
            </thead>
            <tbody>
              <% cycle.workouts.each do |workout| %>
              <tr>
                <td><%= workout.name %></td>
                <td><%= workout.grouptype.try(:name) %></td>
                <td><%= workout.exercise.try(:name) %></td>
                <td><%= workout.equipment.try(:name) %></td>
                <td><%= workout.serie %></td>
                <td><%= workout.sequence %></td>
                <td><%= workout.load %></td>
                <td><%= workout.obs %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <% end %>
      <%= link_to 'Voltar', gymcards_path(client_id: @client) %>
    </div>
  </div>
</div>

app/views/gymcards/show.pdf.erb
<!-- Visão geral do site -->
<div class="panel panel-default">
  <div class="panel-heading main-color-bg">
    <h1 class="panel-title"><%= @gymcard.name %></h1>
  </div>
  <div class="panel-body">
    <div class="col-md-12">
      <div>
        <table class ="table table-striped table-hover" >
          <tbody>
            <tr>
              <th>Cliente</th>
              <td class="td-name"><%= @gymcard.client.name.capitalize %></td>
            </tr>
            <tr>
              <th>Profissional</th>
              <td class="td-name"><%= @gymcard.employee.name.capitalize %> </td>
            </tr>
          </tbody>
        </table>
      </div>

      <% @gymcard.cycles.each do |cycle| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h1 class="panel-title"><%= cycle.name %></h1>
        </div>
        <div class="panel-body">
          <table class ="table table-striped" >
            <thead>
              <tr>
                <th>Nome:</th>
                <th>Equipamento:</th>
                <th>Série:</th>
                <th>Sequência:</th>
                <th>Peso:</th>
                <th>obs:</th>
              </tr>
            </thead>
            <tbody>
              <% cycle.workouts.each do |workout| %>
              <tr>
                <td class="td-name"><%= workout.name.capitalize %></td>
                <td class="td-name"><%= workout.equipment.name.capitalize %></td>
                <td><%= workout.serie %></td>
                <td><%= workout.sequence %></td>
                <td><%= workout.load %></td>
                <td><%= workout.obs %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <% end %>
      
    </div>
  </div>
</div>